### ISSUE TITLE
[1.18.1] Oxidized Copper Podium does not display placed book

### ISSUE THREAD

**Issue by Not-February** [pale-imitations/schools_of_magic#12]
The guidebook can be applied and taken off of the podium with right click and shift right click with it or an empty hand respectively, but the interactive book doesn't pop up above it like it does with the andesite podium I have(and what I assume to be intended behavior), making the copper podium I made for decorative purposes fairly useless.

![image](https://user-images.githubusercontent.com/13922447/148894298-d9656890-2076-44b3-bfa8-184c6bc46c80.png)
![image](https://user-images.githubusercontent.com/13922447/148894343-2ca64787-3621-4134-8186-dc89f2f5c233.png)

The book *is* placed on the podium in the second image, if I shift-right click the podium with an empty hand I get the book back.

Schools of Magic: Second Semester 3.0.07
Forge 39.0.16
Minecraft 1.18.1

**Comment by UdoMorgenstern** [comment]
validated fix in SoMSecondSemester1.18.1-3.0.10
all podiums showing items as expected

![2022-04-26_11 09 58](https://user-images.githubusercontent.com/90903255/165265519-941504f2-3388-40f8-8e02-70ec8f5f3034.png)
