### ISSUE TITLE
Crash on placing a plate

### ISSUE THREAD

**Issue by VallenFrostweaver** [pale-imitations/schools_of_magic#16]
Minecraft 1.18.1
Forge 39.0.64
SoM:2ndS 3.0.0.7

Upon placing a white plate on a gras dirt block the game crashed with this: [https://www.toptal.com/developers/hastebin/akacevovoh.properties](https://www.toptal.com/developers/hastebin/akacevovoh.properties)
Trying to get back into the game continues the crash.

**Comment by UdoMorgenstern** [comment]
FYI: same issue using higher forge versions, this is related to a change in forge version Forge 39.0.64 (create mod had similar issue)

**Comment by UdoMorgenstern** [comment]
validated fix in 1.18.1-3.0.09 and higher

**Comment by pale-imitations** [comment]
I’m really sorry I’ve been MIA, I’m a big fan of your bit by bits. You series on Witchery got me into that mod, which ended up inspiring me to make schools of magic. 

Can confirm, this is fixed as of 3.0.09

**Comment by VallenFrostweaver** [comment]
Thanks for the mod, fix, and kind words! <3
