### ISSUE TITLE
SoMSecondSemester 1.18.1-3.0.10 incompatible with 1.18.2 

### ISSUE THREAD

**Issue by UdoMorgenstern** [pale-imitations/schools_of_magic#19]
Forge: 
40.1.0

SoMSS version:
SoMSecondSemester1.18.1-3.0.10.jar

Log snipped:
[logsnipped.txt](https://github.com/pale-imitations/schools_of_magic/files/8561196/logsnipped.txt)

Mod loading fails because registry is already frozen when custom receipts being registered.
1.18.2 now requires to use DeferredRegister

**Comment by UdoMorgenstern** [comment]
**Test Results SoMSecondSemester1.18.2-3.1.2:**
Smoke test ok
quest works (only tested golem)
basic tea brewing (only tested one kind)
basic spell casting ok
tested: 
 - blaze
 - fast forward (on sweet berry bush, cactus, carrots, sheep)
 - zephyr
 - snowball
 - fuel furness (on normal furness)
 - sundry (on sponge), growth (on grass)
 - shulker bullet
 - healing
 - summon bees
 - fang mangle
 - invisibility
 - translocation
 - thunderstroke
 - posidons_fist failed
Progression no longer reset when exiting the end (resolves last issue mentioned #8)

new issues seen:
- mortar not working
-- seems to miss receipt for crushing white terracotta into white_clay_powder 
-- also tested dried cornflower and dried poppy 
- posidons_fist, missing text/graphic in book
![2022-05-09_11 44 38](https://user-images.githubusercontent.com/90903255/167390617-8785f9d2-1f66-400a-a00b-6cfdd0b16837.png)

old issues seen:
plates not returning items placed on them when breaking plate

Not sure if a letter should drop at 100%
tested withes and evokers - no drop

**Comment by UdoMorgenstern** [comment]
Fyi: using positions fist will leave behind entity.schoolsofmagic:poseidons_fist
can only be remove by command
/kill @e[type=schoolsofmagic:poseidons_fist]

**Comment by pale-imitations** [comment]
Heya, sorry I’ve been MIA, I really appreciate the work you’ve been putting into archiving these issues, it’s really helped me sift through what is actively broken.

The mortar issue is my next project, not sure what happened but I’ll get to the bottom of it. As far as Poseidon’s fist, I apologize, I was supposed to remove access to that before posting the last version, it isn’t ready for player use yet.

**Comment by UdoMorgenstern** [comment]
no worries, such things like the Poseidon's fist happen
tested 1.18.1-3.1.3
 - all new issues fixed
 - old bug related to plates not returning item discussed in discord

one remark when crushing white terracotta in the mortar  it somehow glitches in the end, like it switches between the white terracotta and the 4 white clay powder back and forward for 1-2 seconds

still closing the issue as this deals with the starting under 1.18.2 in general

Great job thanks a lot
Udo / Taxi
