### ISSUE TITLE
Restarting magic level on death

### ISSUE THREAD

**Issue by cogrinn** [pale-imitations/schools_of_magic#8]
Hey, got up to level like 22 in the magic stuff, was having fun flying and what not, went to the end and died, we have corails graveyard which might mess it up since it puts everything in a grave. Once i picked my stuff up im back to level 1 magic

**Comment by raqbit** [comment]
Also had my levels & spells disappear when going through the end dimension and back

**Comment by UdoMorgenstern** [comment]
SchoolsOfMagic1.18.1-3.0.07:
levels & spells no longer disappear on death, but still on exiting the end thru the portal (using waystone mod, not reset happens)

**Comment by TheComputerizer** [comment]
Yep, can confirm that the spells and spell level gets reset when you go back through the end portal. It happened to me twice, which was rather annoying

**Comment by pale-imitations** [comment]
Fixed as of SoMSS v 3.1.2
